version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t thingless/mailglove:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push thingless/mailglove:$TAG
          docker tag thingless/mailglove:$TAG thingless/mailglove:latest
          docker push thingless/mailglove:latest
    branches:
      only: master
